_security_login:
    pattern:  /login
    defaults: { _controller: ShortenerBundle:Default:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/
    defaults: { _controller: ShortenerBundle:Default:protected }

shortener_homepage:
    path:     /
    defaults: { _controller: ShortenerBundle:Default:index }

shortener_expander:
    path:     /{key}
    defaults: { _controller: ShortenerBundle:Default:expand }

shortener_shrinker:
    path:     /shrink_/{full_url}
    defaults: { _controller: ShortenerBundle:Default:shrink }
    requirements:
            full_url: .+