ttb_shortener_homepage:
    path:     /
    defaults: { _controller: TtbShortenerBundle:Default:index }

ttb_shortener_expander:
    path:     /{key}
    defaults: { _controller: TtbShortenerBundle:Default:expand }

ttb_shortener_shrinker:
    path:     /shrink_/{full_url}
    defaults: { _controller: TtbShortenerBundle:Default:shrink }
    requirements:
            full_url: .+