ttb_shortener_homepage:
    path:     /shrink
    defaults: { _controller: TtbShortenerBundle:Default:index }

ttb_shortener_shrinker:
    path:     /shrink/{url}
    defaults: { _controller: TtbShortenerBundle:Default:shrink }