ShortenerBundle\Entity\Abbreviation:
    type: entity
    table: abbreviation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        clue:
            type: string
            length: 255
        fullUrl:
            type: string
            length: 255
    manyToOne:
        userId:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id